version: '3.8'

services:
  app:
    image: php:7.4-apache
    container_name: i-smart-web
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: i-smart-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ismart
    ports:
      - "3306:3306"
